config/routes.rb
Rails.application.routes.draw do

  
  
  
  resources :users

  resource :session

  resources :comments

  resources :homes
  
  
   root :to => "homes#index"
   post '/register' => 'users#create'
   get "/contact" => "comments#new", :as => "contact"
   post "/new_contact" => "comments#new", :as => "post_contact"
   get "/privacy" => "homes#privacy", :as => "privacy"
   post "/new_contact" => "comments#new", :as => "new_contact"
   get "/portfolio" => "homes#portfolio", :as => "portfolio"
   get  "/signup" => "users#new", :as => "signup"
   post  "/login" => "session#new", :as => "login"
   get "/logout" => "session#destroy", :as => "logout"
   get "/activate/:activation_code" => "users#activate", :activation_code => nil, :as => "activate"

  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
  
  
end

app/models/home.rb
=begin
class Home < ActiveRecord::Base
end
=end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.xml
  def index
=begin
    @homes = Home.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @homes }
    end
=end
  end

  # GET /homes/1
  # GET /homes/1.xml
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @home }
    end
  end
  
 

  # GET /homes/new
  # GET /homes/new.xml
  def new
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @home }
    end
  end

  # GET /homes/1/edit
  def edit
    @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.xml
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        flash[:notice] = 'Home was successfully created.'
        format.html { redirect_to(@home) }
        format.xml  { render :xml => @home, :status => :created, :location => @home }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @home.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.xml
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        flash[:notice] = 'Home was successfully updated.'
        format.html { redirect_to(@home) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @home.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.xml
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to(homes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/contact.html.erb
<script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-6347033-2");
  pageTracker._trackPageview();
  } catch(err) {}
</script>
      




<title>Contact me</title>
<br>
<p class="large">We are always happy to hear from you, you can contact me through this site using this link:
   <br/><%= link_to "Post a message", post_contact_path %></p><br/>
<p class="large"> or you can always contact me via email using this link: <br/>  <a href="mailto:jkropka@oneoriginalgeek.com">here</a></p>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% @home.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% form_for(@home) do |f| %>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-6347033-2");
  pageTracker._trackPageview();
  } catch(err) {}
</script>

<p class="large"> After a long career as a hardware technician (hey I was writing DCL code on a DEC-10), then
    another equally long career as a software technician and then engineer - building applications with Microsoft technology
    (anyone else remember VB3?), OneOriginalGeek has spent the past seven years building websites on a contract basis, using
    PHP for a couple of years and then switching over to Ruby on Rails in 2005. </p>
<br/>
<p class="large">This site is published by a coder with lots of experiences (both good and bad).
  You can check out some of my experiences if you visit the blog, &nbsp; <a href="http://blog.oneoriginalgeek.com"> Ramblings on Rails</a> -
  .

app/views/homes/new.html.erb
<h1>New home</h1>

  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% @home.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% form_for(@home) do |f| %>
 <%= f.error_messages %>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', homes_path %>

app/views/homes/portfolio.html.erb
<center><h1>Some Projects I have Worked On</h1></center>
<div class="portfolio_column">
  <div class="portfolio_entry">
    <%= link_to image_tag("portfolio/blabble.png"), "http://blabble.com", :popup => ['blabble', 'width=1200,height=600'] %>
    <p class="large">
      <b>Blabble.com</b> is a "safe" place for teens to interact, it included parental controls
      so that parents could keep an eye on what their teens do online. I built the
      Parent section and the billing portion of the system
    </p>
  </div>


  <div class="portfolio_entry">
    <%= link_to image_tag("portfolio/Forge.png"), "http://forgenow.org", :popup => ['forge', 'width=1000,height=600'] %>
    <p class="large"><b>Forgenow.org</b> is a non-profit organization that allows users to make donations to
      causes in Africa. I was responsible for adding paypal payments and various other site changes the client requested.
    </p> 
  </div>


  <div class="portfolio_entry">
    <%= link_to image_tag("portfolio/Students_know.png"), "http://studentsknow.com", :popup => ['Students Know', 'width=1000,height=600'] %>
    <p class="large">
      <b>Studentsknow.com</b> is a site where students sign up for free to share education videos.  I worked with one other
         developer to deliver the entire site. 
    </p>
  </div>

</div>

<div class="portfolio_column">
  <div class="portfolio_entry">
    <%= link_to image_tag("portfolio/e2g2.png"), "http://e2g2.com", :popup => ['e2g2', 'width=1000,height=600'] %>
    <p class="large">
      <b>E2g2.com</b> is a point of licensure website. I was responsible for building a templating system so admin users
      could build the license application forms.
    </p>
    
  </div>

  <div class="portfolio_entry">
    <%= link_to image_tag("portfolio/RiledUp.png"), "http://riledup.com", :popup => ['Riled Up', 'width=1000,height=600'] %>
    <p class="large">
      <b>RiledUp.com</b> is an online debating site. Users register to create and contribute to debates. They earn experience points
      based on ratings of their posts by other users. I worked with one other developer to deliver the entire site.
    </p>
  </div>
</div>



<div style="clear:both;"></div>
<br/><br/>

app/views/homes/privacy.html.erb
<script type="text/javascript">
  try {
  var pageTracker = _gat._getTracker("UA-6347033-2");
  pageTracker._trackPageview();
  } catch(err) {}
</script>


<br/>
<p class="large"> Whatever you say here stays here. I do not plan to make anything you
post here public - including, but not limited to, comments to the blog and the contact information you may supply
on the "Contact Us" page. </p>

app/views/homes/show.html.erb
<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>