config/routes.rb
Rails.application.routes.draw do

  
  
  
  resources :users

  resource :session

  resources :comments

  resources :homes
  
  
   root :to => "homes#index"
   post '/register' => 'users#create'
   get "/contact" => "comments#new", :as => "contact"
   post "/new_contact" => "comments#new", :as => "post_contact"
   get "/privacy" => "homes#privacy", :as => "privacy"
   post "/new_contact" => "comments#new", :as => "new_contact"
   get "/portfolio" => "homes#portfolio", :as => "portfolio"
   get  "/signup" => "users#new", :as => "signup"
   post  "/login" => "session#new", :as => "login"
   get "/logout" => "session#destroy", :as => "logout"
   get "/activate/:activation_code" => "users#activate", :activation_code => nil, :as => "activate"

  get ':controller/:action/:id'
  get ':controller/:action/:id.:format'
  
  
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <%= link_to "Home", root_path %> &nbsp;|&nbsp;
  <a href="http://blog.oneoriginalgeek.com">Blog</a> &nbsp;|&nbsp;
  <%= link_to "Contact", contact_path%> &nbsp;|&nbsp;
  <%= link_to "Portfolio", portfolio_path%> &nbsp;|&nbsp;
  <%= link_to "Privacy Policy", privacy_path %> &nbsp;|&nbsp;
  <% unless logged_in? %>
    <%= link_to "Admin Login", login_path %> 
  <% else %>
    <%= link_to "View Comments", comments_path %> &nbsp;|&nbsp;
    <%= link_to "Admin Logout", logout_path %> 
  <% end %>
  <br/><br/>    Copyright 2008 OneOriginalGeek.com

</div> <!-- /footer -->

app/views/layouts/_nav.html.erb
<div id="menu">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><a href="http://blog.oneoriginalgeek.com">Blog</a> </li>
    <!-- ><li><%#= link_to "Contact", contact_path%></li> -->
    <li><%= link_to "Portfolio", portfolio_path %> </li>
    <li><%= link_to "Privacy Policy", privacy_path %> </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oneoriginalgeek4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/comments.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>Comments: <%= controller.action_name %></title>
    <%= stylesheet_link_tag 'style' %>
  </head>
  <body>
    <div id="floater">
      <div id="header"><span class="logo"><%= link_to(image_tag("oneoriginalgeek_blue.png"), root_path) %></span></div>
      <%= render :partial => "layouts/nav"%>
    <div class="clear"></div>
    <div id="content">
      <div id="form_div">
        <p style="color: green"><%= flash[:notice] %></p>

        <%= yield  %>
      </div>
    </div>
    <%= render :partial => "layouts/footer" %>
    </div> <!-- floater -->
  </body>
</html>

app/views/layouts/homes.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <% if controller.action_name == "index" %>
    <title>OneOriginalGeek.com Home</title>
  <% elsif controller.action_name == "privacy" %>
    <title>OneOriginalGeek.com Privacy Policy</title>
  <% else %>
    <title>OneOriginalGeek.com <%= controller.action_name.capitalize %></title>
  <% end %>

  <%= stylesheet_link_tag 'style' %>
    <%#= stylesheet_link_tag 'scaffold' %>
  <%#= javascript_include_tag 'prototype'%>
  <%#= javascript_include_tag 'scriptaculous'%>
  <%#= javascript_include_tag 'lightbox'%>
</head>
<body>

  <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  </script>

      
    <div id="floater">
      <div id="header"><span class="logo"><%= link_to(image_tag("oneoriginalgeek_blue.png"), root_path) %></span></div>
      <%= render :partial => "layouts/nav" %>
      <div class="clear"></div>

      <div id="content">
        <% if flash[:notice] %>
          <p style="color: green"><%= flash[:notice] %></p>
          <br/>
        <%end%>
        <% if flash[:error] %>
          <p style="color: red"><%= flash[:error] %></p>
          <br/>
        <% end %>
        <%= yield  %>
       
      </div>
       <br/>
       <center>
         Copyright (c) 2008-2010 OneOriginalGeek.com
       </center>
      <%= render :partial => "layouts/footer" %>
        <div class="clear"></div>

    </div> <!-- floater -->
  </body>
</html>